/*

 DIAL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 9
   Tile set      : C:\Users\Matheo\Desktop\diag.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define box_diagWidth 20
#define box_diagHeight 9
#define box_diagBank 0
#define dial_spriteBank 0

extern unsigned char box_diag[];
extern unsigned char dial_sprite[];

/* End of DIAL.H */
