//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_logo_H
#define METASPRITE_logo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define logo_TILE_ORIGIN 0
#define logo_TILE_W 8
#define logo_TILE_H 8
#define logo_WIDTH 160
#define logo_HEIGHT 144
#define logo_TILE_COUNT 74
#define logo_PALETTE_COUNT 1
#define logo_COLORS_PER_PALETTE 4
#define logo_TOTAL_COLORS 4
#define logo_MAP_ATTRIBUTES 0
extern const unsigned char logo_map[360];
#define logo_map_attributes logo_map

BANKREF_EXTERN(logo)

extern const palette_color_t logo_palettes[4];
extern const uint8_t logo_tiles[1184];

#endif
