//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_logo_H
#define METASPRITE_logo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

extern const int logo_tile_map_size;
extern const int logo_tile_map_width;
extern const int logo_tile_map_height;

extern const int logo_tile_data_size;
extern const int logo_tile_count;

extern const unsigned char logo_tile_data[];
extern const unsigned char logo_map_data[];

#endif
