//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_scene1_H
#define METASPRITE_scene1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scene1_TILE_ORIGIN 0
#define scene1_TILE_W 8
#define scene1_TILE_H 8
#define scene1_WIDTH 128
#define scene1_HEIGHT 128
#define scene1_TILE_COUNT 204
#define scene1_PALETTE_COUNT 1
#define scene1_COLORS_PER_PALETTE 4
#define scene1_TOTAL_COLORS 4
#define scene1_MAP_ATTRIBUTES 0
extern const unsigned char scene1_map[256];
#define scene1_map_attributes scene1_map

BANKREF_EXTERN(scene1)

extern const palette_color_t scene1_palettes[4];
extern const uint8_t scene1_tiles[3264];

#endif
